
package com.cn.xww.webservice.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "HelloServicePortType", targetNamespace = "http://service.xww.cn.com")
public interface HelloServicePortType {

	/**
	 * 
	 * @param in0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://service.xww.cn.com")
	@RequestWrapper(localName = "sayHello", targetNamespace = "http://service.xww.cn.com", className = "com.cn.xww.webservice.client3.SayHello")
	@ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://service.xww.cn.com", className = "com.cn.xww.webservice.client3.SayHelloResponse")
	public String sayHello(@WebParam(name = "in0", targetNamespace = "http://service.xww.cn.com") String in0);

}
