
package com.cn.xww.webservice.client2;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
* IDispatchControl service = new IDispatchControl();
* IDispatchControlPortType portType = service.getIDispatchControlHttpPort();
* portType.dispatchCommand(...);
 * </pre>
 * </p>
 * 
 */
@WebServiceClient(name = "IDispatchControl", targetNamespace = "http://control.ppcore.haobai.huateng.com", wsdlLocation = "http://flowpackage.bestpay.com.cn/flowpackage/services/businessService?wsdl")
public class IDispatchControl extends Service {

	private final static URL IDISPATCHCONTROL_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.cn.xww.webservice.client2.IDispatchControl.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.cn.xww.webservice.client2.IDispatchControl.class.getResource(".");
			url = new URL(baseUrl, "http://flowpackage.bestpay.com.cn/flowpackage/services/businessService?wsdl");
		} catch (MalformedURLException e) {
			logger.warning(
					"Failed to create URL for the wsdl Location: 'http://flowpackage.bestpay.com.cn/flowpackage/services/businessService?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		IDISPATCHCONTROL_WSDL_LOCATION = url;
	}

	public IDispatchControl(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public IDispatchControl() {
		super(IDISPATCHCONTROL_WSDL_LOCATION,
				new QName("http://control.ppcore.haobai.huateng.com", "IDispatchControl"));
	}

	/**
	 * 
	 * @return returns IDispatchControlPortType
	 */
	@WebEndpoint(name = "IDispatchControlHttpPort")
	public IDispatchControlPortType getIDispatchControlHttpPort() {
		return super.getPort(new QName("http://control.ppcore.haobai.huateng.com", "IDispatchControlHttpPort"),
				IDispatchControlPortType.class);
	}

}
